create table if not exists public.interview_sessions (
    id bigint generated by default as identity primary key,
    session_id varchar(255) not null unique,
    owner_id varchar(255),
    candidate_data jsonb not null,
    status varchar(32) not null default 'active',
    question_count integer not null default 0,
    turn_count integer not null default 0,
    covered_curriculum_days jsonb not null default '[]'::jsonb,
    current_curriculum_day integer,
    current_topic varchar(500),
    current_challenge jsonb,
    workspace_snapshot jsonb not null default '{}'::jsonb,
    structured_scores jsonb not null default '{}'::jsonb,
    completion_state jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    completed_at timestamptz,
    constraint interview_sessions_status_check check (status in ('active', 'completed')),
    constraint interview_sessions_question_count_check check (question_count >= 0),
    constraint interview_sessions_turn_count_check check (turn_count >= 0),
    constraint interview_sessions_current_day_check check (
        current_curriculum_day is null
        or current_curriculum_day between 1 and 31
    )
);

create index if not exists ix_interview_sessions_session_id
    on public.interview_sessions (session_id);
create index if not exists ix_interview_sessions_owner_id
    on public.interview_sessions (owner_id);
create index if not exists ix_interview_sessions_status
    on public.interview_sessions (status);
create index if not exists ix_interview_sessions_owner_updated
    on public.interview_sessions (owner_id, updated_at desc);

create table if not exists public.interview_turns (
    id bigint generated by default as identity primary key,
    session_id varchar(255) not null references public.interview_sessions(session_id) on delete cascade,
    sequence integer not null,
    role varchar(32) not null,
    kind varchar(64) not null default 'message',
    content text not null,
    payload jsonb,
    created_at timestamptz not null default now(),
    constraint uq_interview_turn_session_sequence unique (session_id, sequence),
    constraint interview_turns_sequence_check check (sequence > 0),
    constraint interview_turns_role_check check (role in ('interviewer', 'candidate'))
);

create index if not exists ix_interview_turns_session_id
    on public.interview_turns (session_id);

alter table public.interview_sessions enable row level security;
alter table public.interview_turns enable row level security;

revoke all on table public.interview_sessions from anon, authenticated;
revoke all on table public.interview_turns from anon, authenticated;
revoke all on sequence public.interview_sessions_id_seq from anon, authenticated;
revoke all on sequence public.interview_turns_id_seq from anon, authenticated;

comment on column public.interview_sessions.owner_id is
    'Verified Supabase Auth user id. Null for public evaluator sessions.';
